plugins {
    id 'java'
    id 'war'
}

group = 'org.opensagetv'
version = '3.2.30'

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

repositories {
    mavenCentral()
}

dependencies {
    compileOnly 'javax.servlet:javax.servlet-api:3.1.0'
}

war {
    archiveFileName = 'SageTVWebPlayer.war'
}
