package org.opensagetv.webplayer;
import java.util.*;
import java.util.concurrent.*;
/** P09 pure-core SPU vector, palette/highlight, stream-disable and generation smoke. */
public final class DvdSpuSmoke{
 static int pass; public static void main(String[]a)throws Exception{core();session();concurrency();System.out.println("DvdSpuSmoke PASS "+pass+"/3");}
 static void core()throws Exception{DvdSpuCore.Diagnostics d=new DvdSpuCore.Diagnostics();DvdSpuCore.Assembler as=new DvdSpuCore.Assembler(d);DvdSpuCore.Decoder de=new DvdSpuCore.Decoder(d);byte[] p=packet();List<DvdSpuCore.Packet> q=as.feed(new DvdSpuCore.Packet(0x20,90000,Arrays.copyOfRange(p,0,7)));truth(q.isEmpty(),"fragment waits");q=as.feed(new DvdSpuCore.Packet(0x20,-1,Arrays.copyOfRange(p,7,p.length)));truth(q.size()==1,"reassembled");List<DvdSpuCore.Frame> f=de.decode(q.get(0));truth(f.size()==1&&f.get(0).w==1&&f.get(0).h==1,"decoded 1x1");int[] clut=new int[16];clut[3]=0x00EB8080;DvdSpuCore.Argb normal=DvdSpuCore.compose(f.get(0),clut,true,DvdSpuCore.Highlight.hidden());truth(normal.rgba.length==4&&(normal.rgba[3]&255)>0,"rgba alpha");DvdSpuCore.Highlight hi=new DvdSpuCore.Highlight(true,10,10,10,10,0xF000F000);DvdSpuCore.Argb h=DvdSpuCore.compose(f.get(0),clut,true,hi);truth(h.rgba.length==4,"highlight compose");pass++;}
 static void session()throws Exception{DvdNativeSession dvd=new DvdNativeSession();dvd.init(0);byte[] nc=new byte[8];writeInt(nc,0,4);writeInt(nc,4,0);dvd.setNewCell(nc);dvd.spu().select(62);dvd.spu().queue().clearAll();byte[] ps=pes(0x20,packet());dvd.push(push(ps));dvd.spu().queue().clearAll();byte[] ctl=new byte[24];writeInt(ctl,0,20);writeInt(ctl,4,10);writeInt(ctl,8,10);writeInt(ctl,12,10);writeInt(ctl,16,10);writeInt(ctl,20,0xF000F000);dvd.setSpuControl(ctl);truth(dvd.spu().queue().size()>0,"menu highlight visible while subtitles off");long g=dvd.generation();dvd.flush();truth(dvd.generation()!=g,"flush generation");dvd.close();pass++;}
 static void concurrency()throws Exception{DvdNativeSession dvd=new DvdNativeSession();dvd.init(0);dvd.setNewCell(new byte[]{0,0,0,4,0,0,0,0});byte[] p=pes(0x20,packet());ExecutorService e=Executors.newFixedThreadPool(2);try{Future<?> writer=e.submit(()->{try{for(int i=0;i<200;i++)dvd.push(push(p));}catch(Exception x){throw new RuntimeException(x);}});Future<?> reader=e.submit(()->{for(int i=0;i<200;i++)dvd.spu().json();});writer.get(5,TimeUnit.SECONDS);reader.get(5,TimeUnit.SECONDS);}finally{e.shutdownNow();dvd.close();}pass++;}
 static byte[] packet(){byte[] a=new byte[29];a[0]=0;a[1]=29;a[2]=0;a[3]=5;a[4]=0x70;int p=5;a[p++]=0;a[p++]=0;a[p++]=0;a[p++]=5;a[p++]=1;a[p++]=3;a[p++]=0x32;a[p++]=0x10;a[p++]=4;a[p++]=(byte)0xff;a[p++]=(byte)0xff;a[p++]=5;a[p++]=0;a[p++]=(byte)0xa0;a[p++]=10;a[p++]=0;a[p++]=(byte)0xa0;a[p++]=10;a[p++]=6;a[p++]=0;a[p++]=4;a[p++]=0;a[p++]=4;a[p++]=(byte)0xff;return a;}
 static byte[] pes(int sub,byte[] spu){int n=9+5+1+spu.length,plen=n-6;byte[] p=new byte[n];p[0]=0;p[1]=0;p[2]=1;p[3]=(byte)0xbd;p[4]=(byte)(plen>>>8);p[5]=(byte)plen;p[6]=(byte)0x80;p[7]=(byte)0x80;p[8]=5;long pts=90000;p[9]=(byte)(0x20|(((pts>>30)&7)<<1)|1);p[10]=(byte)(pts>>22);p[11]=(byte)((((pts>>15)&127)<<1)|1);p[12]=(byte)(pts>>7);p[13]=(byte)(((pts&127)<<1)|1);p[14]=(byte)sub;System.arraycopy(spu,0,p,15,spu.length);return p;}
 static byte[] push(byte[] p){byte[] b=new byte[p.length+8];writeInt(b,0,p.length);writeInt(b,4,0);System.arraycopy(p,0,b,8,p.length);return b;} static void writeInt(byte[]b,int o,int v){b[o]=(byte)(v>>>24);b[o+1]=(byte)(v>>>16);b[o+2]=(byte)(v>>>8);b[o+3]=(byte)v;}static void truth(boolean x,String m){if(!x)throw new AssertionError(m);}
}
