package org.opensagetv.webplayer;

import java.io.*;
import java.util.*;

/**
 * Platform-neutral DVD SPU core adapted from opensagetv-vibe-android-client
 * commit f1ba340e05fe18eaaba939253a933c3dfe6d6caf (Apache-2.0 project).
 * No Android classes are used; output is straight-alpha RGBA for the browser.
 */
final class DvdSpuCore {
    static final class Diagnostics { long fragments,completed,malformed,decoded,presented,cleared,stale; }
    static final class Packet { final int streamId; final long pts90k; final byte[] data; Packet(int s,long p,byte[] d){streamId=s;pts90k=p;data=d;} }
    static final class Highlight { final boolean visible; final int x1,y1,x2,y2,paletteWord; Highlight(boolean v,int a,int b,int c,int d,int p){visible=v;x1=a;x2=b;y1=c;y2=d;paletteWord=p;} static Highlight hidden(){return new Highlight(false,0,0,-1,-1,0);} boolean contains(int x,int y){return visible&&x>=x1&&x<=x2&&y>=y1&&y<=y2;} }
    static final class Frame { final long serial,event90k; final int streamId,x,y,w,h; final boolean display,forced; final byte[] pixels; final int[] color,alpha; Frame(long s,int id,long e,boolean d,boolean f,int x,int y,int w,int h,byte[] p,int[] c,int[] a){serial=s;streamId=id;event90k=e;display=d;forced=f;this.x=x;this.y=y;this.w=w;this.h=h;pixels=p;color=c;alpha=a;} }
    static final class Argb { final long serial,event90k; final int x,y,w,h; final boolean display; final byte[] rgba; Argb(long s,long e,int x,int y,int w,int h,boolean d,byte[] r){serial=s;event90k=e;this.x=x;this.y=y;this.w=w;this.h=h;display=d;rgba=r;} }

    static final class Assembler {
        private static final int MAX=128*1024; private final Buf[] streams=new Buf[32]; final Diagnostics d;
        Assembler(Diagnostics d){this.d=d;for(int i=0;i<streams.length;i++)streams[i]=new Buf();}
        synchronized List<Packet> feed(Packet f){ArrayList<Packet> out=new ArrayList<Packet>();if(f==null||f.data==null||f.data.length==0)return out;int n=f.streamId-0x20;if(n<0||n>=32)return out;d.fragments++;Buf b=streams[n];if(b.size+f.data.length>MAX){d.malformed++;b.reset();if(f.data.length>MAX)return out;}b.append(f.data,f.pts90k);int c=0;while(b.size-c>=2){int sz=u16(b.data,c);if(sz<4||sz>65535){d.malformed++;c++;continue;}if(b.size-c<sz)break;out.add(new Packet(f.streamId,b.ptsAt(c),Arrays.copyOfRange(b.data,c,c+sz)));d.completed++;c+=sz;}b.compact(c);return out;}
        synchronized void reset(){for(Buf b:streams)b.reset();}
        private static final class Mark{int o;final long p;Mark(int o,long p){this.o=o;this.p=p;}}
        private static final class Buf{byte[] data=new byte[4096];int size;final ArrayList<Mark> m=new ArrayList<Mark>();void append(byte[] s,long p){if(p>=0)m.add(new Mark(size,p));if(size+s.length>data.length)data=Arrays.copyOf(data,Math.min(MAX,Math.max(size+s.length,data.length*2)));System.arraycopy(s,0,data,size,s.length);size+=s.length;}long ptsAt(int o){long p=-1;for(Mark x:m){if(x.o>o)break;p=x.p;}return p;}void compact(int c){if(c<=0)return;if(c>=size){reset();return;}System.arraycopy(data,c,data,0,size-c);size-=c;ArrayList<Mark> n=new ArrayList<Mark>();long anchor=-1;for(Mark x:m){if(x.o<=c)anchor=x.p;else n.add(new Mark(x.o-c,x.p));}m.clear();if(anchor>=0)m.add(new Mark(0,anchor));m.addAll(n);}void reset(){size=0;m.clear();}}
    }

    static final class Decoder {
        final Diagnostics d; long serial=1; Decoder(Diagnostics d){this.d=d;}
        synchronized List<Frame> decode(Packet p){ArrayList<Frame> out=new ArrayList<Frame>();try{decode0(p,out);}catch(Exception e){d.malformed++;out.clear();}d.decoded+=out.size();return out;}
        private void decode0(Packet p,List<Frame> out)throws Exception{if(p==null||p.data==null||p.data.length<4)throw new IOException();byte[] a=p.data;int declared=u16(a,0),ctrl=u16(a,2);if(declared<4||declared>a.length||ctrl<4||ctrl>declared-4)throw new IOException();Params st=new Params();int seq=ctrl,guard=0;while(seq>=ctrl&&seq+4<=declared){if(++guard>512)throw new IOException();int date=u16(a,seq),next=u16(a,seq+2),end=(next>seq&&next<=declared)?next:declared,c=seq+4,action=0;boolean dirty=false,ended=false;long event=p.pts90k<0?-1:p.pts90k+(long)date*1024L;while(c<end){int cmd=u8(a,c++);switch(cmd){case 0x00:st.forced=true;st.display=true;action=1;break;case 0x01:st.display=true;action=1;break;case 0x02:st.display=false;action=2;break;case 0x03:need(c,2,end);int col=u16(a,c);st.color[3]=(col>>>12)&15;st.color[2]=(col>>>8)&15;st.color[1]=(col>>>4)&15;st.color[0]=col&15;c+=2;dirty=true;break;case 0x04:need(c,2,end);int al=u16(a,c);st.alpha[3]=(al>>>12)&15;st.alpha[2]=(al>>>8)&15;st.alpha[1]=(al>>>4)&15;st.alpha[0]=al&15;c+=2;dirty=true;break;case 0x05:need(c,6,end);st.x1=(u8(a,c)<<4)|(u8(a,c+1)>>>4);st.x2=((u8(a,c+1)&15)<<8)|u8(a,c+2);st.y1=(u8(a,c+3)<<4)|(u8(a,c+4)>>>4);st.y2=((u8(a,c+4)&15)<<8)|u8(a,c+5);c+=6;dirty=true;break;case 0x06:need(c,4,end);st.top=u16(a,c);st.bottom=u16(a,c+2);c+=4;dirty=true;break;case 0x07:need(c,2,end);int n=u16(a,c);if(n<2||c+n>end)throw new IOException();c+=n;dirty=true;break;case 0xff:ended=true;c=end;break;default:throw new IOException();}}if(!ended)throw new IOException();if(action==2){out.add(new Frame(serial++,p.streamId,event,false,st.forced,0,0,0,0,new byte[0],new int[4],new int[4]));st.forced=false;}else if(st.display&&(action==1||dirty))out.add(render(p.streamId,event,st,a,ctrl));if(next==seq)break;if(next<ctrl||next>declared-4)throw new IOException();seq=next;}}
        private Frame render(int id,long event,Params s,byte[] a,int rleEnd)throws Exception{if(s.x2<s.x1||s.y2<s.y1)throw new IOException();int w=s.x2-s.x1+1,h=s.y2-s.y1+1;if(w<=0||h<=0||w>2048||h>2048||s.top<4||s.top>=rleEnd||(h>1&&(s.bottom<4||s.bottom>=rleEnd)))throw new IOException();byte[] pix=new byte[w*h];field(a,s.top,rleEnd,pix,w,h,0);if(h>1)field(a,s.bottom,rleEnd,pix,w,h,1);return new Frame(serial++,id,event,true,s.forced,s.x1,s.y1,w,h,pix,s.color.clone(),s.alpha.clone());}
        private static void field(byte[] a,int off,int end,byte[] p,int w,int h,int first)throws Exception{Nib n=new Nib(a,off,end);for(int y=first;y<h;y+=2){n.align();int x=0,runs=0;while(x<w){if(++runs>w+64)throw new IOException();int code=rle(n);if(code<0)throw new IOException();int len=code>>>2,color=code&3;if(len==0)len=w-x;if(len>w-x)throw new IOException();Arrays.fill(p,y*w+x,y*w+x+len,(byte)color);x+=len;}}}
        private static int rle(Nib n){int v=n.read();if(v<0)return -1;if(v<4){int x=n.read();if(x<0)return -1;v=(v<<4)|x;if(v<0x10){x=n.read();if(x<0)return -1;v=(v<<4)|x;if(v<0x40){x=n.read();if(x<0)return -1;v=(v<<4)|x;}}}return v;}
        private static final class Params{int x1,x2=-1,y1,y2=-1,top=-1,bottom=-1;final int[] color={0,1,2,3},alpha={0,15,15,15};boolean forced,display;}
        private static final class Nib{final byte[] a;final int end;int n;Nib(byte[] a,int o,int e){this.a=a;n=o*2;end=Math.min(a.length,e)*2;}int read(){if(n<0||n>=end)return -1;int b=u8(a,n>>>1),v=(n&1)==0?b>>>4:b&15;n++;return v;}void align(){if((n&1)!=0)n++;}}
    }

    static Argb compose(Frame f,int[] clut,boolean clutValid,Highlight h){if(f==null||!f.display||f.w<=0||f.h<=0)return new Argb(f==null?0:f.serial,f==null?-1:f.event90k,0,0,0,0,false,new byte[0]);byte[] rgba=new byte[f.w*f.h*4];int[] normal=palette(f.color,f.alpha,clut,clutValid);int[] hp=h!=null&&h.visible?palette(buttonColors(h.paletteWord),buttonAlpha(h.paletteWord),clut,clutValid):null;for(int y=0;y<f.h;y++)for(int x=0;x<f.w;x++){int slot=f.pixels[y*f.w+x]&3,argb=hp!=null&&h.contains(f.x+x,f.y+y)?hp[slot]:normal[slot],o=(y*f.w+x)*4;rgba[o]=(byte)(argb>>>16);rgba[o+1]=(byte)(argb>>>8);rgba[o+2]=(byte)argb;rgba[o+3]=(byte)(argb>>>24);}return new Argb(f.serial,f.event90k,f.x,f.y,f.w,f.h,true,rgba);}
    private static int[] palette(int[] idx,int[] alpha,int[] clut,boolean valid){int[] r=new int[4];for(int i=0;i<4;i++)r[i]=valid&&clut!=null&&clut.length>=16?toArgb(clut[idx[i]&15],alpha[i]):fallback(i,alpha[i]);return r;}
    private static int[] buttonColors(int w){return new int[]{(w>>>16)&15,(w>>>20)&15,(w>>>24)&15,(w>>>28)&15};}private static int[] buttonAlpha(int w){return new int[]{w&15,(w>>>4)&15,(w>>>8)&15,(w>>>12)&15};}
    private static int toArgb(int ycc,int a4){int y=(ycc>>>16)&255,cr=(ycc>>>8)&255,cb=ycc&255,a=(a4&15)*17;int r=clamp((298*y+459*cr-63514)>>8),g=clamp((298*y-55*cb-136*cr+19681)>>8),b=clamp((298*y+541*cb-73988)>>8);return(a<<24)|(r<<16)|(g<<8)|b;}private static int fallback(int s,int a4){int[] l={0,255,128,0};int v=l[s&3],a=(a4&15)*17;return(a<<24)|(v<<16)|(v<<8)|v;}private static int clamp(int v){return v<0?0:Math.min(255,v);}private static int u8(byte[] a,int o){return a[o]&255;}private static int u16(byte[] a,int o){return(u8(a,o)<<8)|u8(a,o+1);}private static void need(int c,int n,int e)throws IOException{if(c<0||n<0||c+n>e)throw new IOException();}
}
