(() => {
  'use strict';
  const $=id=>document.getElementById(id), State=window.SageSessionState, App=window.SageWebPlayerApp;
  let recordings=[],history={items:[]},favorites={favorites:[]},tuners={devices:[],qualities:[]},dvr={scheduled:[],conflicts:[]};
  let sleepHandle=null,sleepEndMode=false;
  const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function jf(url,opt){const r=await fetch(url,Object.assign({cache:'no-store'},opt||{}));let j;try{j=await r.json();}catch(_){throw new Error(`HTTP ${r.status}`)}if(!r.ok)throw new Error(j.error||`HTTP ${r.status}`);return j;}
  function fmt(sec){sec=Math.max(0,Math.floor(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`;}
  function byId(id){return recordings.find(x=>Number(x.id)===Number(id));}
  function miniRow(item,opts){opts=opts||{};const id=Number(item.id||item.mediaId)||0;const title=item.title||'(untitled)',sub=[item.episode,item.channelNumber&&item.channelName?`${item.channelNumber} ${item.channelName}`:(item.channelNumber||item.channelName),item.start?new Date(item.start).toLocaleString():null].filter(Boolean).join(' · ');const art=item.thumbnailUrl||'';
    const el=document.createElement('div');el.className='mini-item';el.innerHTML=`${art?`<img src="${esc(art)}" alt="">`:''}<div class="mini-item-text"><strong>${esc(title)}</strong><span>${esc(sub)}</span></div>`;
    const a=document.createElement('div');a.className='mini-actions';if(id>0){const p=document.createElement('button');p.textContent=opts.live?'Live':'Play';p.onclick=async()=>{if(await App.loadMedia(id,0,true))App.startAuto();};a.appendChild(p);}if(opts.removeQueue&&id>0){const r=document.createElement('button');r.textContent='Remove';r.onclick=()=>{State.setQueued(id,false);renderQueue();renderHome();};a.appendChild(r);}el.appendChild(a);return el;
  }
  function fillMini(rootId,items,opts){const root=$(rootId);if(!root)return;root.innerHTML='';if(!items||!items.length){root.textContent='None.';return;}items.slice(0,8).forEach(x=>root.appendChild(miniRow(x,opts)));}

  function renderProfiles(){if(!State||!$('profileSelect'))return;const sel=$('profileSelect'),active=State.getActiveProfile();sel.innerHTML='';State.getProfiles().forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.name;sel.appendChild(o)});sel.value=active;}
  $('profileSelect')?.addEventListener('change',e=>{State.setActiveProfile(e.target.value);location.reload();});
  $('addProfile')?.addEventListener('click',()=>{const name=prompt('New local web-player profile name:');if(!name)return;try{const p=State.createProfile(name);State.setActiveProfile(p.id);location.reload();}catch(e){alert(e.message)}});
  $('removeProfile')?.addEventListener('click',()=>{const id=State.getActiveProfile();if(id==='default'){alert('The Default profile cannot be removed.');return;}if(confirm('Remove this browser-local profile and its resume/settings data?')){State.removeProfile(id);location.reload();}});
  $('exportSettings')?.addEventListener('click',()=>{const data=JSON.stringify(State.exportProfile(),null,2),blob=new Blob([data],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`sagetv-webplayer-${State.getActiveProfile()}-profile.json`;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},1000);});
  $('importSettings')?.addEventListener('click',()=>$('importSettingsFile').click());
  $('importSettingsFile')?.addEventListener('change',async e=>{const f=e.target.files&&e.target.files[0];if(!f)return;try{State.importProfile(JSON.parse(await f.text()));location.reload();}catch(err){alert(`Import failed: ${err.message}`)}finally{e.target.value=''}});


  function selectedRecordingIds(){return Array.from(document.querySelectorAll('.bulk-select:checked')).map(x=>Number(x.dataset.mediaId)).filter(x=>x>0);}
  async function bulkWatched(watched){const ids=selectedRecordingIds();if(!ids.length){alert('Select one or more recordings first.');return;}if(!confirm(`${watched?'Mark':'Clear watched state for'} ${ids.length} selected recording${ids.length===1?'':'s'} in SageTV?`))return;for(const id of ids){await jf(`api/library?id=${id}&action=${watched?'watched':'unwatched'}`,{method:'POST'});}await App.loadRecordings();await loadHome();}
  $('bulkWatched')?.addEventListener('click',()=>bulkWatched(true));
  $('bulkUnwatched')?.addEventListener('click',()=>bulkWatched(false));
  $('bulkQueue')?.addEventListener('click',()=>{const ids=selectedRecordingIds();if(!ids.length){alert('Select one or more recordings first.');return;}ids.forEach(id=>State.setQueued(id,true));renderQueue();renderHome();});

  function renderQueue(){const q=State&&State.getQueue?State.getQueue():[];fillMini('queueList',q.map(byId).filter(Boolean),{removeQueue:true});const b=$('queueCurrent'),m=App&&App.getMedia?App.getMedia():null;if(b&&m){const on=State.isQueued(m.id);b.textContent=on?'✓ Queued':'＋ Queue';b.classList.toggle('active',on);}}
  $('clearQueue')?.addEventListener('click',()=>{if(State){State.clearQueue();renderQueue();renderHome();}});
  $('playQueue')?.addEventListener('click',async()=>{const q=State.getQueue();if(!q.length)return;const id=q[0];if(await App.loadMedia(id,0,true))App.startAuto();});
  $('queueCurrent')?.addEventListener('click',()=>{const m=App.getMedia();if(!m)return;State.toggleQueue(m.id);renderQueue();});

  async function loadHistory(){try{history=await jf(`api/history?days=${encodeURIComponent($('historyDays')?.value||30)}`);fillMini('historyList',history.items||[]);return history}catch(e){if($('historyList'))$('historyList').textContent=`History unavailable: ${e.message}`;return{items:[]}}}
  $('refreshHistory')?.addEventListener('click',loadHistory);$('historyDays')?.addEventListener('change',loadHistory);

  async function favoriteAction(id,action,params){const q=new URLSearchParams({favoriteId:String(id),action});Object.entries(params||{}).forEach(([k,v])=>q.set(k,String(v)));await jf(`api/favorites?${q}`,{method:'POST'});await loadFavorites();}
  function renderFavorites(){const root=$('serverFavorites');if(!root)return;root.innerHTML='';const rows=favorites.favorites||[];if(!rows.length){root.textContent='No SageTV Favorites.';return;}rows.forEach((f,idx)=>{const el=document.createElement('article');el.className='rule-item';const flags=[f.enabled?'enabled':'disabled',f.firstRuns&&f.reRuns?'first runs + re-runs':f.firstRuns?'first runs':f.reRuns?'re-runs':'all airings',f.channel?`channel ${f.channel}`:null,f.network?`network ${f.network}`:null,f.quality||null,`${f.startPaddingSeconds||0}s before / ${f.stopPaddingSeconds||0}s after`,f.keepAtMost?`keep ${f.keepAtMost}`:'unlimited'].filter(Boolean).join(' · ');el.innerHTML=`<div><strong>${esc(f.title||f.description||'Favorite')}</strong><div class="small">${esc(flags)}</div></div>`;const a=document.createElement('div');a.className='rule-actions';
      if(idx>0){const up=document.createElement('button');up.textContent='↑ Priority';up.title='Raise above previous Favorite';up.onclick=()=>favoriteAction(f.id,'priority',{otherFavoriteId:rows[idx-1].id,higher:true});a.appendChild(up);}if(idx<rows.length-1){const down=document.createElement('button');down.textContent='↓ Priority';down.title='Lower below next Favorite';down.onclick=()=>favoriteAction(f.id,'priority',{otherFavoriteId:rows[idx+1].id,higher:false});a.appendChild(down);}const en=document.createElement('button');en.textContent=f.enabled?'Disable':'Enable';en.onclick=()=>favoriteAction(f.id,'enabled',{enabled:!f.enabled});a.appendChild(en);
      const pad=document.createElement('button');pad.textContent='Padding';pad.onclick=()=>{const b=prompt('Seconds before start:',String(f.startPaddingSeconds||0));if(b==null)return;const e=prompt('Seconds after end:',String(f.stopPaddingSeconds||0));if(e==null)return;favoriteAction(f.id,'padding',{startSeconds:b,stopSeconds:e});};a.appendChild(pad);
      const run=document.createElement('button');run.textContent='Runs';run.onclick=()=>{const mode=prompt('Run mode: first, reruns, or both',f.firstRuns&&f.reRuns?'both':f.firstRuns?'first':'reruns');if(!mode)return;favoriteAction(f.id,'runs',{firstRuns:mode!=='reruns',reRuns:mode!=='first'});};a.appendChild(run);
      const qual=document.createElement('button');qual.textContent='Quality';qual.onclick=()=>{const choices=(tuners.qualities||[]).map(x=>x.name).join(', '),q=prompt(`Recording quality${choices?` (${choices})`:''}:`,f.quality||'');if(q!=null)favoriteAction(f.id,'quality',{quality:q});};a.appendChild(qual);
      const keep=document.createElement('button');keep.textContent='Retention';keep.onclick=()=>{const n=prompt('Keep at most (0 = unlimited):',String(f.keepAtMost||0));if(n==null)return;const ad=confirm('Allow SageTV to auto-delete old recordings when needed?');favoriteAction(f.id,'keep',{keepAtMost:n,autoDelete:ad});};a.appendChild(keep);
      const del=document.createElement('button');del.className='danger subtle';del.textContent='Remove';del.onclick=()=>{if(confirm(`Remove SageTV Favorite rule “${f.title||'Favorite'}”?`))favoriteAction(f.id,'remove',{confirm:'DELETE'});};a.appendChild(del);el.appendChild(a);root.appendChild(el);});}
  async function loadFavorites(){try{favorites=await jf('api/favorites');renderFavorites();return favorites}catch(e){if($('serverFavorites'))$('serverFavorites').textContent=`Favorites unavailable: ${e.message}`;return{favorites:[]}}}
  $('refreshFavorites')?.addEventListener('click',loadFavorites);
  $('favoriteAddForm')?.addEventListener('submit',async e=>{e.preventDefault();const q=new URLSearchParams({action:'add',title:$('favoriteTitle').value,firstRuns:String($('favoriteFirstRuns').checked),reRuns:String($('favoriteReRuns').checked)});try{await jf(`api/favorites?${q}`,{method:'POST'});$('favoriteTitle').value='';await loadFavorites();}catch(err){alert(err.message)}});

  function renderTuners(){const root=$('tunerList');if(!root)return;root.innerHTML='';const devs=tuners.devices||[];$('tunerSummary').innerHTML='';const sum=document.createElement('span');sum.textContent=`${devs.length} capture device${devs.length===1?'':'s'} · global default quality: ${tuners.defaultQuality||'unknown'}`;$('tunerSummary').appendChild(sum);const gb=document.createElement('button');gb.textContent='Change global quality';gb.style.marginLeft='10px';gb.onclick=async()=>{const names=(tuners.qualities||[]).map(x=>x.name).join(', '),v=prompt(`Global default recording quality${names?` (${names})`:''}:`,tuners.defaultQuality||'');if(v==null)return;await jf(`api/tuners?action=globalQuality&quality=${encodeURIComponent(v)}`,{method:'POST'});loadTuners();};$('tunerSummary').appendChild(gb);if(!devs.length){root.textContent='No capture devices reported.';return;}devs.forEach(d=>{const el=document.createElement('article');el.className='tuner-item';const inputs=(d.inputs||[]).map(i=>`${i.name}${i.lineup?` [${i.lineup}]`:''}${i.signal>=0?` signal ${i.signal}`:''}`).join(' · ');el.innerHTML=`<div><strong>${esc(d.name)}</strong><div class="small">${esc([d.functioning?'functioning':'NOT functioning',d.networkEncoder?'network encoder':null,d.active?'active':null,d.liveClient?'live client':null,d.broadcastStandard,d.currentMediaId?`recording MediaFile ${d.currentMediaId}`:null].filter(Boolean).join(' · '))}</div><div class="small">${esc(inputs)}</div></div>`;const a=document.createElement('div');a.className='tuner-actions';const q=document.createElement('button');q.textContent=`Quality: ${d.defaultQuality||'default'}`;q.onclick=async()=>{const value=prompt(`Default quality for ${d.name}:\n${(d.qualities||[]).join(', ')}`,d.defaultQuality||'');if(value==null)return;await jf(`api/tuners?action=deviceQuality&device=${encodeURIComponent(d.name)}&quality=${encodeURIComponent(value)}`,{method:'POST'});loadTuners();};a.appendChild(q);const merit=document.createElement('button');merit.textContent=`Merit ${d.merit}`;merit.onclick=async()=>{const v=prompt('Encoder merit (0–100):',String(d.merit||0));if(v==null)return;await jf(`api/tuners?action=merit&device=${encodeURIComponent(d.name)}&merit=${encodeURIComponent(v)}`,{method:'POST'});loadTuners();};a.appendChild(merit);el.appendChild(a);root.appendChild(el);});}
  async function loadTuners(){try{tuners=await jf('api/tuners');renderTuners();return tuners}catch(e){if($('tunerList'))$('tunerList').textContent=`Tuner state unavailable: ${e.message}`;return{devices:[],qualities:[]}}}
  $('refreshTuners')?.addEventListener('click',loadTuners);

  async function editRecordingOptions(x){if(!x||!x.airingId)return;try{const o=await jf(`api/recording-options?airingId=${x.airingId}`);if(!o.manualRecord){alert('This is not a manual recording. Create a manual recording first.');return;}const b=prompt('Start padding in seconds:',String(o.startPaddingSeconds||0));if(b==null)return;const e=prompt('Stop padding in seconds:',String(o.stopPaddingSeconds||0));if(e==null)return;const choices=(o.qualities||[]).join(', '),q=prompt(`Recording quality${choices?` (${choices})`:''}:`,o.quality||'');if(q==null)return;const p=new URLSearchParams({airingId:String(x.airingId),startPaddingSeconds:b,stopPaddingSeconds:e,quality:q});await jf(`api/recording-options?${p}`,{method:'POST'});await App.loadGuide();await loadDvr();}catch(err){alert(`Recording options failed: ${err.message}`)}}
  async function loadDvr(){try{dvr=await jf('api/dvr');return dvr}catch(_){return{scheduled:[],conflicts:[]}}}

  function renderHome(){const cont=recordings.filter(r=>!r.recording&&((State.getResume(r.id,0)&&State.getResume(r.id,0).position>15)||Number(r.serverResumeSeconds)>15)).slice(0,8);const live=recordings.filter(r=>r.recording).slice(0,8);fillMini('homeContinue',cont);fillMini('homeRecording',live,{live:true});fillMini('homeDvr',(dvr.scheduled||[]).slice(0,8));fillMini('homeHistory',(history.items||[]).slice(0,8));renderQueue();const q=State.getQueue().length;$('homeSummary').textContent=`Profile: ${State.getActiveProfile()} · ${recordings.length} recordings · ${live.length} recording now · ${(dvr.scheduled||[]).length} scheduled · ${(dvr.conflicts||[]).length} conflicts · ${q} queued`;}
  async function loadHome(){try{const [r,h,d]=await Promise.all([jf('api/recordings?limit=500'),loadHistory(),loadDvr()]);recordings=r.recordings||[];history=h;dvr=d;renderHome();}catch(e){$('homeSummary').textContent=`Home dashboard unavailable: ${e.message}`}}
  $('refreshHome')?.addEventListener('click',loadHome);

  function setSleepTimer(value){if(sleepHandle){clearTimeout(sleepHandle);sleepHandle=null;}sleepEndMode=false;if(value==='end'){sleepEndMode=true;return;}const mins=Number(value)||0;if(mins>0)sleepHandle=setTimeout(()=>{document.getElementById('stop')?.click();alert(`SageTV Web Player sleep timer (${mins} min) stopped playback.`);$('sleepTimer').value='0';},mins*60000);}
  $('sleepTimer')?.addEventListener('change',e=>setSleepTimer(e.target.value));
  setInterval(()=>{if(!sleepEndMode)return;const m=App.getMedia&&App.getMedia();if(!m||m.recording)return;const seek=$('seek');if(seek&&!seek.disabled&&Number(seek.max)>0&&Number(seek.value)>=Number(seek.max)-2){sleepEndMode=false;$('stop')?.click();$('sleepTimer').value='0';}},1000);

  $('pictureInPicture')?.addEventListener('click',async()=>{try{let v=null;if(document.getElementById('playerStage')?.classList.contains('native'))v=$('nativeVideo');else v=document.querySelector('#fallbackPlayer video');if(!v){alert('Picture-in-Picture is available for native or compatibility video playback.');return;}if(document.pictureInPictureElement)await document.exitPictureInPicture();else if(v.requestPictureInPicture)await v.requestPictureInPicture();else if(v.webkitSetPresentationMode)v.webkitSetPresentationMode('picture-in-picture');else alert('This browser does not expose Picture-in-Picture.');}catch(e){alert(e.message)}});

  window.SageAdvancedUI={refreshHome:loadHome,renderQueue,editRecordingOptions,loadFavorites,loadTuners,loadHistory};
  renderProfiles();Promise.all([loadHome(),loadFavorites(),loadTuners()]).then(renderHome);
})();
