/* P14 diagnostics/profile helpers. No credentials, media payloads or subtitle text
 * belong in diagnostic/profile artifacts. Browser identity and per-session track
 * indexes are deliberately outside exported saved-default profiles. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.SageMiniSupport=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const PROFILE_SCHEMA=1,PROFILE_KIND='sagetv-webplayer-profile';
const CLIENT_KEYS=['bufferPreset','startSegments','maxBufferSeconds','uiResolution','osdTrigger','clickMode','guideAssist','mouseBack','showStats','renderOnly','videoMaskAssist','videoFit','videoViewport','displayPolicyVersion','mute','fullscreenOnConnect','inputMode','unifiedGraphics','autoDiagnosticCapture','saveDiagnosticsToServer'];
const STREAM_KEYS=['player','videoMode','encoder','videoKbps','keyFrameSeconds','bFrames','resolution','fps','deinterlace','audioCodec','audioKbps','audioChannels','audioLanguage','audioFallback','audioOffsetMs','captionAuthority','captions','captionService','captionPage','captionLanguage','captionOffsetMs','subtitleMode','subtitleLanguage','subtitleOffsetMs','subtitleForcedOnly','allowFallback'];
const CAPTION_KEYS=['mode','cc1Type','cc1Language','cc1Service','cc2Type','cc2Language','cc2Service'];
const SENSITIVE=/(authorization|cookie|password|passwd|secret|token|credential|session.?key|crypto|private.?key|share.?user|share.?pass)/i;
const CONTENT=/(payload|subtitle.?text|caption.?text|media.?bytes|raw.?data|cue.?data)/i;
function pick(source,keys){const out={};source=source&&typeof source==='object'?source:{};for(const k of keys)if(Object.prototype.hasOwnProperty.call(source,k))out[k]=source[k];return out;}
function keysUnknown(source,allowed,prefix,out){source=source&&typeof source==='object'?source:{};for(const k of Object.keys(source))if(!allowed.includes(k)&&out.length<50)out.push((prefix?prefix+'.':'')+k);}
function buildProfile(client,streaming,captions){return{kind:PROFILE_KIND,schemaVersion:PROFILE_SCHEMA,profileScope:'browser-saved-defaults',createdAt:new Date().toISOString(),excludedScopes:['client-identity','per-session-track-pid-selection','administrator-server-settings'],savedDefaults:{client:pick(client,CLIENT_KEYS),streaming:pick(streaming,STREAM_KEYS),captions:pick(captions,CAPTION_KEYS)}};}
function previewProfile(input){let p=input;if(typeof p==='string')p=JSON.parse(p);if(!p||typeof p!=='object'||p.kind!==PROFILE_KIND)throw new Error('Not a SageTV WebPlayer profile');const schema=Number(p.schemaVersion)||0;if(schema<1||schema>PROFILE_SCHEMA)throw new Error('Unsupported profile schema '+schema);const d=p.savedDefaults||{},unknown=[];keysUnknown(p,['kind','schemaVersion','profileScope','createdAt','excludedScopes','savedDefaults'],'',unknown);keysUnknown(d,['client','streaming','captions'],'savedDefaults',unknown);keysUnknown(d.client,CLIENT_KEYS,'client',unknown);keysUnknown(d.streaming,STREAM_KEYS,'streaming',unknown);keysUnknown(d.captions,CAPTION_KEYS,'captions',unknown);return{schemaVersion:schema,unknownKeys:unknown,migrations:schema<PROFILE_SCHEMA?['schema '+schema+' → '+PROFILE_SCHEMA]:[],client:pick(d.client,CLIENT_KEYS),streaming:pick(d.streaming,STREAM_KEYS),captions:pick(d.captions,CAPTION_KEYS)};}
function redact(value,depth){depth=depth||0;if(depth>8)return'[depth-limit]';if(value==null||typeof value==='number'||typeof value==='boolean')return value;if(typeof value==='string')return value.length>4096?value.slice(0,4096)+'…[truncated]':value;if(Array.isArray(value))return value.slice(0,256).map(v=>redact(v,depth+1));if(typeof value!=='object')return String(value);const out={};let count=0;for(const k of Object.keys(value)){if(count++>=256){out._truncatedKeys=true;break;}if(SENSITIVE.test(k))out[k]='[redacted]';else if(CONTENT.test(k))out[k]='[omitted-content]';else out[k]=redact(value[k],depth+1);}return out;}
function captionSummary(authority,effective,inventory,captionSnap,ordinary,dvdSpu){const track=effective&&effective.track||null,stvLocal=!!(effective&&effective.mode==='stv'&&captionSnap&&captionSnap.stvControlled);return{authority:authority&&authority.mode||'off',resolvedSlot:stvLocal&&captionSnap.stvService?String(captionSnap.stvService):effective&&/^cc[12]$/.test(effective.mode||'')?effective.mode.toUpperCase():null,renderOwner:stvLocal?'browser-local-stv-controlled':effective&&effective.mode==='stv'?'sage-stv':effective&&effective.local&&effective.local!=='off'?'browser-local':'off',effectiveType:stvLocal?'608':effective&&effective.local||'off',codec:track&&track.codec||null,pid:track&&Number.isFinite(Number(track.sourcePid))?Number(track.sourcePid):null,page:track&&Number.isFinite(Number(track.teletextPage))?Number(track.teletextPage):null,service:stvLocal&&captionSnap.stvService?Number(String(captionSnap.stvService).replace(/^CC/i,''))||null:effective&&effective.service||null,language:track&&track.language||null,discoveredTracks:Array.isArray(inventory)?inventory.length:0,queuePending:captionSnap&&captionSnap.pending||0,received:captionSnap&&captionSnap.received||0,stvStateSeen:captionSnap&&captionSnap.stvStateSeen||false,stvState:captionSnap&&Number.isFinite(Number(captionSnap.stvState))?Number(captionSnap.stvState):null,ordinary:ordinary?{mode:ordinary.mode,received:ordinary.received,clears:ordinary.clears,pending:ordinary.pending,bitmapExpiry:ordinary.bitmapExpiry,error:ordinary.error,queue:ordinary.queue||null}:null,dvdSpu:dvdSpu?{active:dvdSpu.active,received:dvdSpu.received,clears:dvdSpu.clears,pending:dvdSpu.pending,error:dvdSpu.error,queue:dvdSpu.queue||null}:null};}
function effectiveTranscode(status){status=status||{};const e=status.streamSettings&&status.streamSettings.effective||{};return{transport:status.transport||null,encoder:status.encoder||e.video||null,accelerator:status.accelerator||null,decodeAccelerator:status.decodeAccelerator||e.decodeAccelerator||null,hardwareEncode:!!status.hardware,hardwareDecode:!!status.hardwareDecode,hardwareFilters:!!status.hardwareFilters,hardwareDecodeFallback:!!status.hardwareDecodeFallback,fallbackStage:Number(status.fallbackStage||0),softwareFallback:!!status.softwareFallback,inputMode:status.inputMode||null,video:e.video||null,audio:e.audio||null,detail:e.detail||e.pipelineDetail||status.inputDetail||null};}
return{PROFILE_SCHEMA,PROFILE_KIND,CLIENT_KEYS,STREAM_KEYS,CAPTION_KEYS,buildProfile,previewProfile,redact,captionSummary,effectiveTranscode};
});
